### ISSUE TITLE
Warnings when installing - ENOENT: no such file or directory, open ... package.json and more

### ISSUE THREAD

**Issue by frederickjh** [aleung/csvsplit#2]
Hi!
This program looks exactly like what I need. Thanks for coding it.
However when I try to install running node.js 12.18.3 using npm per the instructions I get the following warnings. 

![image](https://user-images.githubusercontent.com/864159/90233110-e7a52880-de1d-11ea-9d25-5c324e057b65.png)

Frederick

**Comment by aleung** [comment]
Thanks for the feedback. Let me take time to check it.

**Comment by aleung** [comment]
The installation command in README was incorrect. It's fixed.

**Comment by frederickjh** [comment]
Commit 88a3cf03 fixes this.

Install CSV split:

`npm install -g @aleung/csvsplit`
